# Generated by Django 4.0.4 on 2022-09-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=255)),
                ('admin_email', models.CharField(blank=True, max_length=255, null=True)),
                ('admin_password', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'AdminData',
                'managed': True,
            },
        ),
    ]
