# Generated by Django 4.0.4 on 2022-09-13 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LIB_API', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admindata',
            table='admindata',
        ),
    ]
