# Generated by Django 4.0.4 on 2022-09-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIB_API', '0002_alter_admindata_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=255)),
                ('book_name', models.CharField(max_length=455)),
                ('book_price', models.CharField(max_length=255)),
                ('book_author', models.CharField(max_length=455)),
                ('book_dateOfPublication', models.CharField(max_length=455)),
                ('book_inlanguage', models.CharField(max_length=455)),
            ],
            options={
                'db_table': 'bookdata',
                'managed': True,
            },
        ),
    ]
